### ISSUE TITLE
Active Admin and Angular Rails Templates Error 'register_engine' no method error class engine

### ISSUE THREAD

**Issue by michaelstokes** [pitr/angular-rails-templates#122]
Hello,

So after installing active admin, adding gem and running bundle install, having angular-rails-templates already installed or not, I would get an error when starting the rails server althought the bundle install would be fine

```
<class:Engine>': undefined method `register_engine' for nil:NilClass (NoMethodError)
```

```
/Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/angular-rails-templates-0.1.4/lib/angular-rails-templates/engine.rb:49:in `block (2 levels) in <class:Engine>': undefined method `register_engine' for nil:NilClass (NoMethodError)
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/angular-rails-templates-0.1.4/lib/angular-rails-templates/engine.rb:39:in `each'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/angular-rails-templates-0.1.4/lib/angular-rails-templates/engine.rb:39:in `block in <class:Engine>'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/michaelstokes/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/michaelstokes/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/michaelstokes/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/michaelstokes/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/michaelstokes/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/michaelstokes/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/michaelstokes/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/michaelstokes/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/michaelstokes/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
	from /Users/michaelstokes/projects/adminangulartemplates/config/environment.rb:5:in `<top (required)>'
	from /Users/michaelstokes/projects/adminangulartemplates/config.ru:3:in `require'
	from /Users/michaelstokes/projects/adminangulartemplates/config.ru:3:in `block in <main>'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /Users/michaelstokes/projects/adminangulartemplates/config.ru:in `new'
	from /Users/michaelstokes/projects/adminangulartemplates/config.ru:in `<main>'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/server.rb:61:in `app'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/server.rb:78:in `start'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/michaelstokes/projects/adminangulartemplates/bin/rails:9:in `require'
	from /Users/michaelstokes/projects/adminangulartemplates/bin/rails:9:in `<top (required)>'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/spring-1.6.0/lib/spring/client/rails.rb:28:in `load'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/spring-1.6.0/lib/spring/client/rails.rb:28:in `call'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/spring-1.6.0/lib/spring/client/command.rb:7:in `call'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/spring-1.6.0/lib/spring/client.rb:28:in `run'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/spring-1.6.0/bin/spring:51:in `<top (required)>'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/spring-1.6.0/lib/spring/binstub.rb:11:in `load'
	from /Users/michaelstokes/.rvm/gems/ruby-2.2.1/gems/spring-1.6.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/michaelstokes/projects/adminangulartemplates/bin/spring:13:in `require'
	from /Users/michaelstokes/projects/adminangulartemplates/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>
```

I'm not too sure as to why this error but if I simply remove the gem 'angular-rails-templates' from the gemfile then the rails server starts without running bundle and then adding it back, the error continues. 

Thank you.

**Comment by michaelstokes** [comment]
Fixed by 

Add to your Gemfile:
gem 'sprockets', '2.12.3'
And run in terminal:
bundle update

https://github.com/pitr/angular-rails-templates/issues/120

Sorry for duplicate issue, I just noticed this occured immediately after installing another gem.
