### ISSUE TITLE
1.0.0.beta1: Bundler::GemRequireError

### ISSUE THREAD

**Issue by bmulholland** [pitr/angular-rails-templates#127]
I upgraded to version 1.0.0.beta1 to test it out, but am getting an error on init (rspec, rails server, anything):

```
/Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'angular-rails-templates'. (Bundler::GemRequireError)
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
        from /Users/bmulholland/dev/coupa_clm/config/application.rb:12:in `<top (required)>'
        from /Users/bmulholland/dev/coupa_clm/config/environment.rb:4:in `require'
        from /Users/bmulholland/dev/coupa_clm/config/environment.rb:4:in `<top (required)>'
        from /Users/bmulholland/dev/coupa_clm/spec/spec_helper.rb:8:in `require'
        from /Users/bmulholland/dev/coupa_clm/spec/spec_helper.rb:8:in `<top (required)>'
        from /Users/bmulholland/dev/coupa_clm/spec/controllers/activations_controller_spec.rb:1:in `require'
        from /Users/bmulholland/dev/coupa_clm/spec/controllers/activations_controller_spec.rb:1:in `<top (required)>'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1361:in `load'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1359:in `each'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:106:in `setup'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:92:in `run'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:78:in `run'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:45:in `invoke'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/gems/rspec-core-3.4.2/exe/rspec:4:in `<top (required)>'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/bin/rspec:23:in `load'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/bin/rspec:23:in `<main>'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/bin/ruby_executable_hooks:15:in `eval'
        from /Users/bmulholland/.rvm/gems/ruby-2.2.3@contractually/bin/ruby_executable_hooks:15:in `<main>'

```

Not a very helpful error or I'd dig into it more myself. I tried the latest on github and received the same error. Let me know if there's anything I can do to help.

**Comment by pitr** [comment]
I believe the issue is with "tilt" gem not being required early enough. Can you try `1.0.0.beta2`

**Comment by bmulholland** [comment]
That did the trick! Thanks again @pitr!
