### ISSUE TITLE
can't modify immutable index

### ISSUE THREAD

**Issue by ehelms** [pitr/angular-rails-templates#83]
We run multiple engines not all of which make use of angular-rails-templates. We are finding that if one of them is loaded prior to the engine that includes angular-rails-templates we get the error in the subject. I'll include below both the intialization process and stack trace. Note that if `foreman_docker` is loaded after `bastion` the isn't an issue as the code hits the sprockets environment.rb instead of the immutable index when register_engine is called.

I am hoping you have some insight or a fix given that I can't necessarily control the load order and the register engine appears to not be restricted to the development/precompile stage.

```
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.12.3/lib/sprockets/index.rb:81:in `expire_index!'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.12.3/lib/sprockets/base.rb:168:in `register_engine'
/opt/rh/ruby193/root/usr/share/gems/gems/angular-rails-templates-0.1.3/lib/angular-rails-templates/engine.rb:49:in `block (2 levels) in <class:Engine>'
/opt/rh/ruby193/root/usr/share/gems/gems/angular-rails-templates-0.1.3/lib/angular-rails-templates/engine.rb:39:in `each'
/opt/rh/ruby193/root/usr/share/gems/gems/angular-rails-templates-0.1.3/lib/angular-rails-templates/engine.rb:39:in `block in <class:Engine>'
/opt/rh/ruby193/root/usr/share/gems/gems/railties-3.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/opt/rh/ruby193/root/usr/share/gems/gems/railties-3.2.8/lib/rails/initializable.rb:30:in `run'
/opt/rh/ruby193/root/usr/share/gems/gems/railties-3.2.8/lib/rails/initializable.rb:56:in `block in run_initializers'
/opt/rh/ruby193/root/usr/share/gems/gems/railties-3.2.8/lib/rails/initializable.rb:54:in `each'
/opt/rh/ruby193/root/usr/share/gems/gems/railties-3.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/opt/rh/ruby193/root/usr/share/gems/gems/railties-3.2.8/lib/rails/application.rb:136:in `initialize!'
/opt/rh/ruby193/root/usr/share/gems/gems/railties-3.2.8/lib/rails/railtie/configurable.rb:30:in `method_missing'
/usr/share/foreman/config/environment.rb:5:in `<top (required)>'
```

```
load_config_initializers
Apipie cache enabled but not present yet. Run apipie:cache rake task to speed up API calls.
Workaround for RbVmomi may not work as ComputeResource is already loaded: ComputeResource
engines_blank_point
engines_blank_point
static assets
engines_blank_point
secure_headers.action_controller
engines_blank_point
turbolinks
engines_blank_point
engines_blank_point
foreman_docker.load_app_instance_data
foreman_docker.assets.precompile
foreman_docker.configure_assets
foreman_docker.register_gettext
define_main_app_helper
add_to_prepare_blocks
run_prepare_callbacks
eager_load!
finisher_hook
foreman_docker.register_plugin
engines_blank_point
bastion.assets.paths
engines_blank_point
angular-rails-templates
rake aborted!
```

**Comment by ehelms** [comment]
Note this change appears to be what leads to the issue - https://github.com/pitr/angular-rails-templates/pull/57 

I will lock our deployment and infrastructure to 0.1.12 for now due to this.

**Comment by pitr** [comment]
closing old task
